# Generated by Django 3.2 on 2021-04-20 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Prairie Sinus Ear Allergy Clinic', max_length=30)),
                ('zip_code', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('phizer_stock', models.IntegerField(default=0)),
                ('moderna_stock', models.IntegerField(default=0)),
                ('janssen_stock', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('services', models.CharField(choices=[('Testing', 'Testing'), ('Vaccination', 'Vaccination'), ('Screening', 'Screening'), ('COVID', 'COVID'), ('All', 'All')], default='All', max_length=11)),
                ('ages', models.CharField(choices=[('Children', 'Children'), ('Adults', 'Adults'), ('Seniors', 'Seniors'), ('Others', 'Others'), ('All', 'All')], default='All', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('number_concurrent_appts', models.IntegerField(default=0)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
            ],
        ),
    ]
