# Generated by Django 3.2 on 2021-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='ages',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='services',
        ),
        migrations.AddField(
            model_name='clinic',
            name='Adults',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='All_Ages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='COVID',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Seniors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='pic_address',
            field=models.CharField(default='https://cdn.upmc.com/-/media/upmc/campaigns/covid-vaccine/vaccineoggraphic.jpg?la=en&rev=3105491e4bd8458199540f68f6ab86f6', max_length=300),
        ),
    ]
