# Generated by Django 3.2 on 2021-04-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20210421_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='COVID',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='Screening',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='Testing',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='Vaccination',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='All_Ages',
            field=models.BooleanField(default=True),
        ),
    ]
